name: Build and Test

on:
  workflow_dispatch:
    
  push:
    branches:
      - main
    paths:
      - 'ChocolateStoreCore\**'
      - 'ChocolateStoreCoreTests\**'
  pull_request:
    branches:
      - main

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_PAT }}
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Update Version
      run: |
        pwsh -File ${{ github.workspace }}\ChocolateStoreCore\version.ps1 -projectDir ${{ github.workspace }}\ChocolateStoreCore

    - name: Restore dependencies ChocolateStoreCore
      run: |
        cd ${{ github.workspace }}\ChocolateStoreCore
        dotnet restore ${{ github.workspace }}\ChocolateStoreCore\ChocolateStoreCore.csproj -r win-x86
              
    - name: Build ChocolateStoreCore
      run: |
        dotnet build ${{ github.workspace }}\ChocolateStoreCore\ChocolateStoreCore.csproj --configuration Release --no-restore
      
    - name: Restore dependencies Tests
      run: |
        cd ${{ github.workspace }}\ChocolateStoreCoreTests\
        dotnet restore -r win-x86
      
    - name: Build Tests
      run: |
        dotnet build ${{ github.workspace }}\ChocolateStoreCoreTests\ChocolateStoreCoreTests.csproj --configuration Release --no-restore
      
    - name: Test
      run: |
        dotnet test ${{ github.workspace }}\ChocolateStoreCoreTests\ChocolateStoreCoreTests.csproj --configuration Release --no-restore --collect:"XPlat Code Coverage"

    - name: Test coverage report generation preparation
      run: |
        if (!(Test-Path -path ${{ github.workspace }}\.github\Workflows\History)) 
        { 
          New-Item -ItemType directory -Force -Path ${{ github.workspace }}\.github\Workflows\History
        }

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.21
      with:
        reports: ${{ github.workspace }}\ChocolateStoreCoreTests\**\coverage.cobertura.xml
        targetdir: ${{ github.workspace }}
        reporttypes: HtmlSummary
        historydir: ${{ github.workspace }}\.github\Workflows\History
        title: 'ChocolateStoreCore Coverage Report'
        license: ${{ secrets.REPORTGENERATOR_LICENSE }}
    
    - name: Commit and push changes
      run: |
        cd ${{ github.workspace }}
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git remote add origin_https https://${{ secrets.GIT_PAT }}@github.com/robertZaufall/ChocolateStoreCore.git
        git add ChocolateStoreCore/ChocolateStoreCore.csproj
        git add ChocolateStoreCore/version.txt
        git add summary.html
        git add ${{ github.workspace }}\.github\Workflows\History
        git commit -m "Incremented build version [skip actions]"
        git push origin_https HEAD:main
      env:
        GIT_PAT: ${{ secrets.GIT_PAT }}
