name: Build and Test

on:
  workflow_dispatch:
    
  # push:
  #   branches:
  #   - main
  # pull_request:
  #   branches:
  #   - main

jobs:
  build:
  
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
        
    - name: Update Version
      run: |
        pwsh -File ${{ github.workspace }}\ChocolateStoreCore\version.ps1 -projectDir ${{ github.workspace }}\ChocolateStoreCore

    - name: Restore dependencies
      run: |
        cd ${{ github.workspace }}\ChocolateStoreCore
        dotnet restore ${{ github.workspace }}\ChocolateStoreCore\ChocolateStoreCore.csproj -f -r win-x86
              
    - name: Build
      run: |
        dotnet build ${{ github.workspace }}\ChocolateStoreCore\ChocolateStoreCore.csproj --configuration Release --no-restore
      
    # - name: Restore dependencies
    #   run: |
    #     cd ${{ github.workspace }}\ChocolateStoreCoreTest\
    #     dotnet restore -r win-x86
      
    # - name: Build
    #   run: dotnet build --configuration Release --no-restore
      
    # - name: Test
    #   run: dotnet test --configuration Release --no-restore

    - name: Commit and push changes
      run: |
        cd ${{ github.workspace }}
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add ChocolateStoreCore/ChocolateStoreCore.csproj
        git add ChocolateStoreCore/version.txt
        git commit -m "Incremented build version"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
