name: OnlyTesting

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
  
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Commit and push changes
      run: |
        cd ${{ github.workspace }}
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git fetch origin
        
        $last_commit="$(git rev-parse HEAD)"
        echo "$last_commit"
        if ($last_commit -ne "${{ github.sha }}") {
          echo "Check-in cancelled due to changes in the meantime."
          exit 0
        }
        echo "Check-in might have been done."
